Update compile-test.

diff --git a/package/src/compile-test b/package/src/compile-test
--- a/package/src/compile-test
+++ b/package/src/compile-test
@@ -11,10 +11,11 @@ builddir=/tmp/OpenRTI-compileTest-$$
 
 case `uname` in
     CYGWIN*)
-        generators[0]="Visual Studio 14 2015 Win64"
-        generators[1]="Visual Studio 14 2015"
+        generators[0]="Visual Studio 17 2022"
         # Puh, cl only understands a single standard that is baken in
-        stdflags[0]=""
+        # But we highjack this to walk the architetures now
+        stdflags[0]="-A Win32"
+        stdflags[1]="-A x64"
         ;;
     Linux*)
         generators[0]=""
@@ -89,6 +90,13 @@ for generator in "${generators[@]}" ; do
                                 exit 1
                             fi
                             ;;
+                        SunOS*)
+                            gmake -j8
+                            if [ "$?" != "0" ] ; then
+                                1>&2 echo "Build step failed."
+                                exit 1
+                            fi
+                            ;;
                         *)
                             make -j8
                             if [ "$?" != "0" ] ; then
@@ -99,7 +107,7 @@ for generator in "${generators[@]}" ; do
                     esac
 
                     case ${buildconfig}`uname` in
-                        *Linux|CYGWIN*Release)
+                        *Linux|Release*CYGWIN*)
                             ctest --buildconfig $buildconfig
                             if [ "$?" != "0" ] ; then
                                 1>&2 echo "Tests failed."
@@ -109,6 +117,7 @@ for generator in "${generators[@]}" ; do
                         *)
                             ;;
                     esac
+                    cd -
                 )
                 if [ "$?" != "0" ] ; then
                     exit 1
